ENV["YELP_DAILY_REQUEST_LIMIT"] ||= "1000"
YELP_REQUEST_LIMIT = ENV["YELP_DAILY_REQUEST_LIMIT"].to_i

ENV["YELP_RATE_LIMIT_WINDOW"]   ||= "#{24*60}" # in minutes
YELP_WINDOW = 60 * ENV["YELP_RATE_LIMIT_WINDOW"].to_i # in seconds

INTERVAL_FOR_YELP_RATE_LIMIT = wait_time_for_request_limit_of(YELP_REQUEST_LIMIT, YELP_WINDOW)